services:
  baseimage:
    build:
      context: ../..
      dockerfile: Sources/docker/Dockerfile.baseImage
    image: baseimage:latest

  fsgfuzz:
    build:
      context: ../..
      dockerfile: Sources/docker/Dockerfile.fsgfuzz
    depends_on:
      - baseimage
    container_name: fsgfuzz
    privileged: true
    volumes:
      - ../..:/workspace/local-code       # 로컬 코드 마운트
      - ../../fuzz_output:/workspace/sgfuzz-for-fprime/fuzz_output  # 퍼징 결과 저장
      - ../../fprime/Svc/CmdDispatcher:/workspace/sgfuzz-for-fprime/fprime/Svc/CmdDispatcher  # 전체 CmdDispatcher 디렉토리 마운트
    environment:
      - COMPONENT_NAME=CmdDispatcher      # 타겟 컴포넌트 이름
      - FUZZ_RUNS=0                       # 실행 횟수 (0=무한)
      - FUZZ_MAX_LEN=1024                 # 최대 입력 크기
      - FUZZ_TIMEOUT=60                   # 타임아웃(초)
      - FUZZ_WORKERS=1                    # 병렬 워커 수
      - KEEP_ALIVE=false                  # 퍼징 후 컨테이너 유지 여부
    tty: true
    stdin_open: true
